// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function make(scopes, webClientId, hostedDomain, offlineAccess, iosClientId, loginHint, forceCodeForRefreshToken, accountName, param) {
  return {
          scopes: scopes,
          webClientId: webClientId,
          hostedDomain: hostedDomain,
          offlineAccess: offlineAccess,
          iosClientId: iosClientId,
          loginHint: loginHint,
          forceCodeForRefreshToken: forceCodeForRefreshToken,
          accountName: accountName
        };
}

var Configure = {
  make: make
};

function make$1(showPlayServicesUpdateDialog) {
  return showPlayServicesUpdateDialog;
}

var HasPlayServicesParams = {
  make: make$1
};

function user(param) {
  return param.user;
}

function scopes(param) {
  return param.scopes;
}

function idToken(param) {
  return param.idToken;
}

function serviceAuthCode(param) {
  return param.serviceAuthCode;
}

function id(param) {
  return param.id;
}

function name(param) {
  return param.name;
}

function email(param) {
  return param.email;
}

function photo(param) {
  return param.photo;
}

function familyName(param) {
  return param.familyName;
}

function givenName(param) {
  return param.givenName;
}

var User = {
  user: user,
  scopes: scopes,
  idToken: idToken,
  serviceAuthCode: serviceAuthCode,
  id: id,
  name: name,
  email: email,
  photo: photo,
  familyName: familyName,
  givenName: givenName
};

function idToken$1(param) {
  return param.idToken;
}

function accessToken(param) {
  return param.accessToken;
}

var Token = {
  idToken: idToken$1,
  accessToken: accessToken
};

export {
  Configure ,
  HasPlayServicesParams ,
  User ,
  Token ,
  
}
/* No side effect */
